name: gigglio
description: "Chat, share, and connect with friends while keeping the giggles going!"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.1+1

# if changed/modified icon, run this command ater changing the path to icon in yaml file
# dart run flutter_native_splash:create --path=native_splash.yaml

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase 
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.2.1
  firebase_crashlytics: ^4.1.3
  # state management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  rxdart: ^0.28.0
  get_it: ^8.0.2
  get_storage: ^2.1.1

  dio: ^5.8.0+1
  go_router: ^15.1.1
  app_links: ^6.3.2
  cached_network_image: ^3.4.1
  responsive_framework: ^0.1.4
  flutter_native_splash: ^2.4.6

  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  flutter_html: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The lint set provided by the package is activated in the `analysis_options.yaml` 
  # file located at the root of your package. 
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/privacy_policy.html

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
